"""
APIx Statistical Index Compilation Package (Phase 29: MoSPI CPI 2024 + Eurostat HICP Aligned).
"""

from .models import (
    MonthlyProductPrice,
    MatchedProduct,
    ElementaryIndexResult,
    LeadTimeIndexResult,
    RouteIndexResult,
    APIxSeriesResult,
)
from .monthly_pricing import compute_monthly_product_prices
from .matching import ProductMatchingEngine
from .jevons import JevonsEngine
from .weights import (
    WeightRegistry,
    normalize_and_validate_weights,
    assert_no_cpi_weight_contamination,
)
from .route_basket import (
    DGCARouteItem,
    DGCARouteBasketConfig,
    DGCA_CY2024_TOP60_BASKET,
    get_dgca_cy2024_top60_basket,
    get_top60_route_weights,
    validate_route_basket,
    BASKET_ID as DGCA_BASKET_ID,
    REFERENCE_PERIOD as DGCA_REFERENCE_PERIOD,
    COVERAGE_PERCENT as DGCA_COVERAGE_PERCENT,
    TOTAL_BASKET_PASSENGER_VOLUME as DGCA_TOTAL_BASKET_PASSENGER_VOLUME,
    TOTAL_ALL_INDIA_PASSENGER_VOLUME as DGCA_TOTAL_ALL_INDIA_PASSENGER_VOLUME,
)
from .lead_time_weights import (
    LeadTimeWeightItem,
    LeadTimeWeightConfig,
    EMPIRICAL_LEAD_TIME_WEIGHTS,
    EQUAL_LEAD_TIME_WEIGHTS,
    get_empirical_lead_time_weights,
    get_equal_lead_time_weights,
    get_lead_time_weight_config,
    validate_lead_time_weights,
    assert_no_cpi_contamination as assert_no_cpi_lead_time_contamination,
    METHODOLOGY_STATUS_EMPIRICAL,
    METHODOLOGY_STATUS_SENSITIVITY,
    METHODOLOGY_STATUS_PROVISIONAL_EQUAL,
    SOURCE_DATASET as LEAD_TIME_SOURCE_DATASET,
    SOURCE_INTERPRETATION as LEAD_TIME_SOURCE_INTERPRETATION,
    DISCLAIMER as LEAD_TIME_DISCLAIMER,
    LEAD_TIME_CLASSES,
)
from .aggregation import IndexAggregationEngine
from .engine import APIxEngine
from .classification import (
    COICOPClassification,
    CPIIntegrationLayer,
    CPIAirfareWeightConfig,
    CPI_AIRFARE_WEIGHT_PERCENT,
    CPI_AIRFARE_WEIGHT_DECIMAL,
    CPI_AIRFARE_ITEM_CODE,
    CPI_AIRFARE_ITEM_DESCRIPTION,
    CPI_REFERENCE_YEAR,
    CPI_WEIGHT_SOURCE,
    CPI_AIRFARE_DISCLAIMER,
)
from .product_definition import (
    FareOffer,
    PriceBreakdown,
    QualityCharacteristics,
    ProductSelectionEngine,
    ItinerarySelectionResult,
    PRODUCT_DEFINITION_VERSION,
    SELECTION_RULE,
)
from .quality_adjustment import (
    QualityAdjustmentEngine,
    ReplacementAuditRecord,
    QualityAdjustmentRecord,
    ObservationStatus,
    ReplacementTreatment,
)
from .flight_schedule import (
    DGCAScheduledFlight,
    DGCAScheduleRegistry,
    FlightUniverseStatus,
    MatchedFlightResult,
    ScraperCoverageReport,
    AmbiguousStationError,
    ScheduleContaminationError,
    normalize_station,
    normalize_flight_number,
    parse_frequency,
    is_flight_active_on_date,
    evaluate_scraper_coverage,
    get_schedule_registry,
    assert_no_schedule_weight_contamination,
)

__all__ = [
    "MonthlyProductPrice",
    "MatchedProduct",
    "ElementaryIndexResult",
    "LeadTimeIndexResult",
    "RouteIndexResult",
    "APIxSeriesResult",
    "compute_monthly_product_prices",
    "ProductMatchingEngine",
    "JevonsEngine",
    "WeightRegistry",
    "normalize_and_validate_weights",
    "assert_no_cpi_weight_contamination",
    "IndexAggregationEngine",
    "APIxEngine",
    "COICOPClassification",
    "CPIIntegrationLayer",
    "CPIAirfareWeightConfig",
    "CPI_AIRFARE_WEIGHT_PERCENT",
    "CPI_AIRFARE_WEIGHT_DECIMAL",
    "CPI_AIRFARE_ITEM_CODE",
    "CPI_AIRFARE_ITEM_DESCRIPTION",
    "CPI_REFERENCE_YEAR",
    "CPI_WEIGHT_SOURCE",
    "CPI_AIRFARE_DISCLAIMER",
    "FareOffer",
    "PriceBreakdown",
    "QualityCharacteristics",
    "ProductSelectionEngine",
    "ItinerarySelectionResult",
    "PRODUCT_DEFINITION_VERSION",
    "SELECTION_RULE",
    "QualityAdjustmentEngine",
    "ReplacementAuditRecord",
    "QualityAdjustmentRecord",
    "ObservationStatus",
    "ReplacementTreatment",
    "DGCARouteItem",
    "DGCARouteBasketConfig",
    "DGCA_CY2024_TOP60_BASKET",
    "get_dgca_cy2024_top60_basket",
    "get_top60_route_weights",
    "validate_route_basket",
    "DGCA_BASKET_ID",
    "DGCA_REFERENCE_PERIOD",
    "DGCA_COVERAGE_PERCENT",
    "DGCA_TOTAL_BASKET_PASSENGER_VOLUME",
    "DGCA_TOTAL_ALL_INDIA_PASSENGER_VOLUME",
    "LeadTimeWeightItem",
    "LeadTimeWeightConfig",
    "EMPIRICAL_LEAD_TIME_WEIGHTS",
    "EQUAL_LEAD_TIME_WEIGHTS",
    "get_empirical_lead_time_weights",
    "get_equal_lead_time_weights",
    "get_lead_time_weight_config",
    "validate_lead_time_weights",
    "assert_no_cpi_lead_time_contamination",
    "METHODOLOGY_STATUS_EMPIRICAL",
    "METHODOLOGY_STATUS_SENSITIVITY",
    "METHODOLOGY_STATUS_PROVISIONAL_EQUAL",
    "LEAD_TIME_SOURCE_DATASET",
    "LEAD_TIME_SOURCE_INTERPRETATION",
    "LEAD_TIME_DISCLAIMER",
    "LEAD_TIME_CLASSES",
    "DGCAScheduledFlight",
    "DGCAScheduleRegistry",
    "FlightUniverseStatus",
    "MatchedFlightResult",
    "ScraperCoverageReport",
    "AmbiguousStationError",
    "ScheduleContaminationError",
    "normalize_station",
    "normalize_flight_number",
    "parse_frequency",
    "is_flight_active_on_date",
    "evaluate_scraper_coverage",
    "get_schedule_registry",
    "assert_no_schedule_weight_contamination",
]
