"""Initial schema

Revision ID: 0449a8b8a8b6
Revises: 
Create Date: 2026-09-21 18:20:07.950245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0449a8b8a8b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_mappings',
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=False),
    sa.Column('canonical_value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_index('ix_entity_mappings_lookup', 'entity_mappings', ['entity_type', 'source', 'raw_value'], unique=False)
    op.create_table('normalization_exceptions',
    sa.Column('exception_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ai_attempted', sa.Boolean(), nullable=False),
    sa.Column('ai_candidate', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('resolution_status', sa.String(length=50), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_index(op.f('ix_normalization_exceptions_observation_id'), 'normalization_exceptions', ['observation_id'], unique=False)
    op.create_table('schema_versions',
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('permitted_method', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('adapter_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'version', name='uq_adapter_source_version')
    )
    op.create_table('collection_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['source_name'], ['sources.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_collection_jobs_run_id'), 'collection_jobs', ['run_id'], unique=False)
    op.create_table('fare_observations',
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('collection_run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_offer_id', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('airline_code', sa.String(length=10), nullable=True),
    sa.Column('flight_number', sa.String(length=50), nullable=True),
    sa.Column('trip_type', sa.String(length=20), nullable=False),
    sa.Column('cabin', sa.String(length=20), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('fare_family', sa.String(length=100), nullable=True),
    sa.Column('fare_class', sa.String(length=20), nullable=True),
    sa.Column('base_fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('raw_value_reference', sa.String(), nullable=True),
    sa.Column('raw_evidence_uri', sa.String(), nullable=True),
    sa.Column('adapter_version', sa.String(length=20), nullable=False),
    sa.Column('normalizer_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['source'], ['sources.name'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index('ix_fare_obs_airline', 'fare_observations', ['airline'], unique=False)
    op.create_index('ix_fare_obs_lead_days', 'fare_observations', ['lead_days'], unique=False)
    op.create_index('ix_fare_obs_route', 'fare_observations', ['origin', 'destination'], unique=False)
    op.create_index(op.f('ix_fare_observations_collected_at'), 'fare_observations', ['collected_at'], unique=False)
    op.create_index(op.f('ix_fare_observations_collection_run_id'), 'fare_observations', ['collection_run_id'], unique=False)
    op.create_index(op.f('ix_fare_observations_travel_date'), 'fare_observations', ['travel_date'], unique=False)
    op.create_table('quality_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['source'], ['sources.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_metrics_collection_run_id'), 'quality_metrics', ['collection_run_id'], unique=False)
    op.create_table('source_health',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('observation_yield', sa.Float(), nullable=True),
    sa.Column('parser_error_rate', sa.Float(), nullable=True),
    sa.Column('validation_error_rate', sa.Float(), nullable=True),
    sa.Column('normalization_error_rate', sa.Float(), nullable=True),
    sa.Column('response_time_p50', sa.Integer(), nullable=True),
    sa.Column('response_time_p95', sa.Integer(), nullable=True),
    sa.Column('rate_limit_count', sa.Integer(), nullable=False),
    sa.Column('access_restriction_count', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_schema_change_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['sources.name'], ),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('validation_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('raw_value', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_errors_collection_run_id'), 'validation_errors', ['collection_run_id'], unique=False)
    op.create_table('raw_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_run_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('collection_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('raw_evidence_uri', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('adapter_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['collection_jobs.request_id'], ),
    sa.ForeignKeyConstraint(['source_name'], ['sources.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_obs_source_time', 'raw_observations', ['source_name', 'collection_timestamp'], unique=False)
    op.create_index(op.f('ix_raw_observations_collection_run_id'), 'raw_observations', ['collection_run_id'], unique=False)
    op.create_index(op.f('ix_raw_observations_request_id'), 'raw_observations', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_observations_request_id'), table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_collection_run_id'), table_name='raw_observations')
    op.drop_index('ix_raw_obs_source_time', table_name='raw_observations')
    op.drop_table('raw_observations')
    op.drop_index(op.f('ix_validation_errors_collection_run_id'), table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_quality_metrics_collection_run_id'), table_name='quality_metrics')
    op.drop_table('quality_metrics')
    op.drop_index(op.f('ix_fare_observations_travel_date'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_collection_run_id'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_collected_at'), table_name='fare_observations')
    op.drop_index('ix_fare_obs_route', table_name='fare_observations')
    op.drop_index('ix_fare_obs_lead_days', table_name='fare_observations')
    op.drop_index('ix_fare_obs_airline', table_name='fare_observations')
    op.drop_table('fare_observations')
    op.drop_index(op.f('ix_collection_jobs_run_id'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_table('adapter_versions')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('schema_versions')
    op.drop_index(op.f('ix_normalization_exceptions_observation_id'), table_name='normalization_exceptions')
    op.drop_table('normalization_exceptions')
    op.drop_index('ix_entity_mappings_lookup', table_name='entity_mappings')
    op.drop_table('entity_mappings')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
